version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: lab3db
      POSTGRES_USER: lab3user
      POSTGRES_PASSWORD: lab3password
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: lab3-frontend
    ports:
      - "8080:8000"  # frontend accesible en localhost:8080
    depends_on:
      - db

volumes:
  db_data:
