services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: lab3db
      POSTGRES_USER: lab3user
      POSTGRES_PASSWORD: lab3password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: